# Generated by Django 4.1.7 on 2023-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_postimage_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
