# Generated by Django 4.1.7 on 2023-03-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"verbose_name": "comment"},
        ),
    ]
