# Generated by Django 4.1.7 on 2023-03-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "comment", "verbose_name_plural": "comments"},
        ),
    ]
