# Generated by Django 4.1.7 on 2023-03-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"verbose_name_plural": "comments"},
        ),
    ]
