# Generated by Django 4.1.7 on 2023-03-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like", old_name="post_likes", new_name="liked_post",
        ),
    ]
