# Generated by Django 4.1.7 on 2023-03-28 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_post_likes_delete_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
